project:
  type: website

website:
  title: "Haoxue's Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - example_analysis.qmd

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

execute: 
  freeze: auto

